# Generated by Django 4.1 on 2022-08-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepName', models.CharField(max_length=500)),
                ('stepDescription', models.CharField(max_length=500)),
                ('params', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=500)),
                ('testDescription', models.CharField(max_length=500)),
                ('stepkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='btest.step')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='testkey',
            field=models.ManyToManyField(to='btest.test'),
        ),
    ]
