# Generated by Django 4.1 on 2022-08-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='testkey',
        ),
    ]
